/**
 * Production asset registry.
 * Keep all paths local so design updates only require dropping files into
 * `public/` and updating keys in this single module.
 */
export const assets = {
  brand: {
    logo: "/icons/png/logo.png",
  },
  home: {
    /** Looping orb texture used in hero, workflow viz, and RCM animation */
    orbVideo: "/videos/home/joy-orb-gradient-loop.mp4",
    orbGradient: "/images/home/orb-gradient.png",
    ellipse25: "/images/home/ellipse-25.png",
    ellipse26: "/images/home/ellipse-26.png",
    ellipse27: "/images/home/ellipse-27.png",
    ellipse28: "/images/home/ellipse-28.svg",
    ellipse29: "/images/home/ellipse-29.svg",
  },
  partners: {
    trusted1: "/images/partners/trusted-1.png",
    trusted2: "/images/partners/trusted-2.png",
    trusted3: "/images/partners/trusted-3.png",
  },
  solutions: {
    precisionHero: "/images/solutions/precision-hero.png",
    engineDiagram: "/images/solutions/engine-diagram.png",
    skillCardVisualization: "/images/solutions/skill-card-visualization.png",
    solutionDental: "/images/landing/illustrations/solution-dental.jpg",
    solutionMedical: "/images/landing/illustrations/solution-medical.jpg",
    solutionRcm: "/images/landing/illustrations/solution-rcm.jpg",
  },
  landing: {
    heroTexture: "/images/landing/illustrations/hero-texture.svg",
    isometricBridge: "/images/landing/illustrations/isometric-bridge.png",
    mockPriorAuth: "/images/landing/illustrations/mock-prior-auth.png",
    growthChart: "/images/landing/illustrations/growth-chart.png",
    icons: {
      voice: "/images/landing/icons/icon-voice.png",
      web: "/images/landing/icons/icon-web.png",
      fax: "/images/landing/icons/icon-fax.png",
      arrowRight: "/images/landing/icons/arrow-right.svg",
    },
    logos: {
      color1: "/images/landing/logos/logo-color-1.png",
      color2: "/images/landing/logos/logo-color-2.png",
      color3: "/images/landing/logos/logo-color-3.png",
      color4: "/images/landing/logos/logo-color-4.png",
      color5: "/images/landing/logos/logo-color-5.png",
      gray1: "/images/landing/logos/logo-gray-1.png",
      gray2: "/images/landing/logos/logo-gray-2.png",
      gray3: "/images/landing/logos/logo-gray-3.png",
      gray4: "/images/landing/logos/logo-gray-4.png",
      gray5: "/images/landing/logos/logo-gray-5.png",
      gray6: "/images/landing/logos/logo-gray-6.png",
      ehr: [
        "/images/logos/ehr/athena-health.png",
        "/images/logos/ehr/carestack.png",
        "/images/logos/ehr/cloud-9.png",
        "/images/logos/ehr/denticon.png",
        "/images/logos/ehr/dentrix-ascend.png",
        "/images/logos/ehr/epic.png",
        "/images/logos/ehr/greenway.png",
        "/images/logos/ehr/modmed.png",
        "/images/logos/ehr/opendental.png",
        "/images/logos/ehr/veradigm.png",
      ],
      payers: [
        "/images/logos/payers/aetna.png",
        "/images/logos/payers/american-specialty-health.png",
        "/images/logos/payers/ameritas.png",
        "/images/logos/payers/anthem.png",
        "/images/logos/payers/blue-shield-california.png",
        "/images/logos/payers/cigna-healthcare.png",
        "/images/logos/payers/delta-dental.webp",
        "/images/logos/payers/guardian.png",
        "/images/logos/payers/humana.jpg",
        "/images/logos/payers/principal.png",
        "/images/logos/payers/quantum-health.png",
        "/images/logos/payers/umr.png",
        "/images/logos/payers/united-healthcare.png",
      ],
    },
  },
  company: {
    /** EHR Ecosystem row on Company — order left → right. */
    ehrEcosystemLogos: [
      { src: "/images/logos/ehr/epic.png", alt: "Epic" },
      { src: "/images/logos/ehr/athena-health.png", alt: "athenahealth" },
      { src: "/images/logos/ehr/modmed.png", alt: "ModMed" },
      { src: "/images/logos/ehr/dentrix-ascend.png", alt: "Dentrix Ascend" },
      { src: "/images/logos/ehr/opendental.png", alt: "Open Dental" },
      { src: "/images/logos/ehr/veradigm.png", alt: "Veradigm" },
    ],
    partners: {
      investorLogos: "/images/company/partners/investor-partner-logos.png",
      /** Company page “Backed by” strip (Cencora, Mayo Clinic, Optum). */
      strip: {
        cencora: "/images/company/partners-strip/cencora.svg",
        mayoClinic: "/images/company/partners-strip/mayo-clinic.svg",
        optum: "/images/company/partners-strip/optum.svg",
      },
    },
    security: {
      shieldIcon: "/images/company/security/security-shield.svg",
      hipaaBadge: "/images/footer/badge-hipaa.png",
      soc2Badge: "/images/footer/badge-soc.png",
      isoBadge: "/images/footer/badge-iso.png",
    },
    team: {
      paragJhaveri: "/images/company/team/parag-jhaveri.png",
      amberDay: "/images/company/team/amber-day.png",
      abhishekPandey: "/images/company/team/abhishek-pandey.png",
      akshayKore: "/images/company/team/akshay-kore.png",
      shubhamKalburgi: "/images/company/team/shubham-kalburgi.png",
      maryGrove: "/images/company/team/mary-grove.png",
      paulConley: "/images/company/team/paul-conley.png",
      andrewVaz: "/images/company/team/andrew-vaz.png",
      brianColao: "/images/company/team/brian-colao.png",
    },
  },
  pricing: {
    icons: {
      location: "/images/pricing/icons/location.png",
      subscription: "/images/pricing/icons/subscription.png",
      capacity: "/images/pricing/icons/capacity.png",
      overage: "/images/pricing/icons/overage.png",
      complexity: "/images/pricing/icons/complexity.png",
      rush: "/images/pricing/icons/rush.png",
      implementation: "/images/pricing/icons/implementation.png",
      calendar: "/images/pricing/icons/calendar.png",
      clock: "/images/pricing/icons/clock.png",
      dropdownChevron: "/images/pricing/icons/dropdown-chevron.png",
    },
  },
  footer: {
    icons: {
      network: "/images/footer/icon-network.png",
      planet: "/images/footer/icon-planet.png",
      sparkle: "/images/footer/icon-sparkle.png",
      sun: "/images/footer/icon-sun.png",
    },
  },
  // Backward-compatible aliases while feature modules migrate to nested keys.
  heroTexture: "/images/landing/illustrations/hero-texture.svg",
  trusted1: "/images/partners/trusted-1.png",
  trusted2: "/images/partners/trusted-2.png",
  trusted3: "/images/partners/trusted-3.png",
  ellipse25: "/images/home/ellipse-25.png",
  ellipse26: "/images/home/ellipse-26.png",
  ellipse27: "/images/home/ellipse-27.png",
  ellipse28: "/images/home/ellipse-28.svg",
  ellipse29: "/images/home/ellipse-29.svg",
  logoColor1: "/images/landing/logos/logo-color-1.png",
  logoColor2: "/images/landing/logos/logo-color-2.png",
  logoColor3: "/images/landing/logos/logo-color-3.png",
  logoColor4: "/images/landing/logos/logo-color-4.png",
  logoColor5: "/images/landing/logos/logo-color-5.png",
  logoGray1: "/images/landing/logos/logo-gray-1.png",
  logoGray2: "/images/landing/logos/logo-gray-2.png",
  logoGray3: "/images/landing/logos/logo-gray-3.png",
  logoGray4: "/images/landing/logos/logo-gray-4.png",
  logoGray5: "/images/landing/logos/logo-gray-5.png",
  logoGray6: "/images/landing/logos/logo-gray-6.png",
  mockPriorAuth: "/images/landing/illustrations/mock-prior-auth.png",
  iconVoice: "/images/landing/icons/icon-voice.png",
  iconWeb: "/images/landing/icons/icon-web.png",
  iconFax: "/images/landing/icons/icon-fax.png",
  arrowRight: "/images/landing/icons/arrow-right.svg",
  solutionDental: "/images/landing/illustrations/solution-dental.jpg",
  solutionMedical: "/images/landing/illustrations/solution-medical.jpg",
  solutionRcm: "/images/landing/illustrations/solution-rcm.jpg",
  isometricBridge: "/images/landing/illustrations/isometric-bridge.png",
  precisionHero: "/images/solutions/precision-hero.png",
  growthChart: "/images/landing/illustrations/growth-chart.png",
} as const;
